server:
  port: 8081

aws:
  dynamodb:
    endpoint: "http://localhost:8000"
  region: "us-east-1"
  accessKeyId: "fakeAccessKeyId"
  secretAccessKey: "fakeSecretAccessKey"

fraud:
  api:
    url: "http://localhost:8080"

spring:
  application:
    name: order-microservice
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-microservice-group
    properties:
      schema.registry.url: http://localhost:8081
    producer:
      properties:
        schema.registry.url: http://localhost:8081

app:
  event:
    source-id: "policy-service-instance-01"

policy:
  kafka:
    topics:
      status-notifications: "policy-status-notifications-topic"
      payment-events: "payment-confirmed-events-topic"
      subscription-events: "subscription-authorized-events-topic"
      dead-letter-queue: "policy-dlq-topic"
