aws:
  dynamodb:
    endpoint: "http://localhost:8000"
  region: "us-east-1"
  accessKeyId: "fakeAccessKeyId"
  secretAccessKey: "fakeSecretAccessKey"

fraud:
  api:
    url: "http://localhost:8080"

logging:
  level:
    com.acmeinsurance.policy: DEBUG
    software.amazon.awssdk: INFO
    org.springframework.cloud.openfeign: DEBUG