aws:
  dynamodb:
    endpoint: "http://localhost:8000"
  region: "us-east-1"
  accessKeyId: "fakeAccessKeyId"
  secretAccessKey: "fakeSecretAccessKey"

logging:
  level:
    com.acmeinsurance.policy: DEBUG
    software.amazon.awssdk: INFO