receivers:
  otlp/grpc:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  otlp/http:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors: {}

extensions:
  health_check: {}

exporters:
  logging:
    loglevel: debug
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    traces:
      receivers: [otlp/grpc, otlp/http]
      exporters: [logging, otlp/jaeger]
    metrics:
      receivers: [otlp/grpc, otlp/http]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp/grpc, otlp/http]
      exporters: [logging]

  extensions: [health_check]