name: Spring Native CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - run: mvn clean install -DskipTests -Dspring-boot.build-image.skip=true

      - uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: target/site/jacoco/jacoco.xml
        if: success()

  build-and-push-native-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


  deploy-and-run-e2e-tests:
    needs: build-and-push-native-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - run: |
          sudo apt-get update && sudo apt-get install -y docker-compose netcat-openbsd
          docker compose -f src/main/resources/docker/docker-compose.yml up -d

      - run: |
          echo "Waiting for DynamoDB Local to be healthy..."
          timeout 300 bash -c 'until [ "$(docker inspect -f {{.State.Health.Status}} dynamodb-local)" = "healthy" ]; do echo -n "."; sleep 5; done' || { echo "DynamoDB Local did not become healthy. Aborting."; exit 1; }
          echo "DynamoDB Local is healthy!"

          echo "Waiting for DynamoDB Initializer to complete setup..."
          timeout 300 bash -c 'until docker inspect dynamodb-initializer &>/dev/null && docker inspect dynamodb-initializer | grep -q "Exited (0)"; do echo -n "."; sleep 10; done' || { echo "DynamoDB Initializer did not complete successfully. Aborting."; exit 1; }
          echo "DynamoDB Local and table setup completed by Initializer!"

      - run: |
          echo "Waiting for Wiremock to be healthy..."
          timeout 120 bash -c 'until [ "$(docker inspect -f {{.State.Health.Status}} wiremock)" = "healthy" ]; do echo -n "."; sleep 5; done' || { echo "Wiremock did not become healthy. Aborting."; exit 1; }
          echo "Wiremock is healthy!"

      - run: |
          echo "Waiting for Kafka and Schema Registry..."
          timeout 300 bash -c 'until [ "$(docker inspect -f {{.State.Health.Status}} control-center)" = "healthy" ]; do echo -n "."; sleep 10; done' || { echo "Kafka or Schema Registry did not become healthy. Aborting."; exit 1; }
          echo "Kafka and Schema Registry are ready!"

      - name: Wait for Order Microservice Native App to Start
        run: |
          echo "Waiting for Order Microservice Native App to start on port 8090..."
          timeout 180 bash -c 'while ! nc -z localhost 8090; do echo -n "."; sleep 5; done' || { echo "Order Microservice Native App did not start. Aborting."; exit 1; }
          echo "Order Microservice Native App is up!"

      - run: mvn integration-test -Dspring-boot.build-image.skip=true

      - if: always()
        run: docker compose -f src/main/resources/docker/docker-compose.yml down
